### ISSUE TITLE
Examples seem to refer to an old API

### ISSUE THREAD

**Issue by hdgone** [pipelined/pipe#101]
Hey guys, thanks for an amazing library, it does everything I needed but I've recently run into an issue.

I'd been playing with the examples repo trying different scenarios but when I actually started moving code for examples to the server codebase I got stuck because the newer API doesn't work as it used to.

For instance, this code wouldn't compile (examples/example_6_test.go):
```	
p, err := pipe.New(
        &pipe.Line{
	// mp3 pump.
	Pump: &mp3.Pump{
		Reader: mp3File,
	},
	// asset sink.
	Sinks: pipe.Sinks(a),
        },
)
```
seems like pipe API has been completely changed.

I'm trying to compile the following on the recent version of pipeline/pipe which is **0.8.2**
This code is compiled on **0.7.0**

Also, I'm not able to install any other version than the latest one for some reason.
I would much appreciate any help on this one!

**Comment by dudk** [comment]
Hello Dave!

Glad to hear that the project is useful. I indeed changed the `pipe` and `signal` packages in recent months to improve memory allocations. Right now I'm going through all repos to make use of it, which should take another month I presume. 

Could you please provide more details on how are you trying to get v0.7.0 and what goes wrong?

**Comment by hdgone** [comment]
Thank you for such a quick response!

I've actually managed to make some progress. Somehow this way of uploading a specific version didn't work for me:

> go get pipelined.dev/pipe@0.7.0

But I solved it by changing the version inside go.mod and running `go mod download`

works perfect, sorry for the rush on this one!

**Comment by dudk** [comment]
Really glad to hear that! Closing it.
